[package]
name = "server_users"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
tokio = { version = "1", features = ["full"] }
ssh2 = "0.9"
anyhow = "1.0"
chrono = "0.4"
